spring.application.name=santander

# API configuration
api.cep.base-url=http://localhost:3000
api.cep.context-path=/v1/consulta

# Database configuration
spring.data.mongodb.host=mongodb://admin:admin123@localhost:27017/?authSource=admin
spring.data.mongodb.database=santanderDB
spring.data.mongodb.username=admin
spring.data.mongodb.password=admin123
spring.datasource.driver-class-name=org.mongodb.Driver